# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BM3Tb3gO0zJ0imCfA88FG2kjyTN_3PoH
"""
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
from sklearn.metrics import precision_score
from sklearn.linear_model import LogisticRegression as lr
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import joblib
import streamlit as st

model = joblib.load('mymodel.joblib')

sen = pipeline('sentiment-analysis',model='HooshvareLab/bert-fa-base-uncased-sentiment-snappfood')

st.title('ویرایشگر نظر خریدار')
sent =  st.text_input('نظر خود را راجب کالا وارد کنید')
ops = st.slider('تعداد نقاط قوت را مشخص کنید', min_value=1, max_value=3, value=1)
neg = st.slider('تعداد نقاط ضعف را مشخص کنید', min_value=1, max_value=3, value=1)
score = st.slider('امتیاز کالا', min_value=1, max_value=5, value=3)
sentf = sen(sent)
if sentf[0]['label'] == 'HAPPY':
  des = 1
else :
  des = 0
def predict():
  raw = np.array([[des,ops,neg]]) # Ensure raw is 2D for DataFrame
  x = pd.DataFrame(raw,columns=['des','ops','neg'])
  pre = model.predict(x)
  if pre[0]==1 and score >= 3 :
    st.success('نظر شما ثبت شد')
  elif pre[0]==1 and score < 3 :
    st.error('لطفا امتیاز مناسب بدهید نظر شما ثبت نشد')
  elif pre[0]==0 and score < 3 :
    st.success('نظر شما ثبت شد')
  elif pre[0]==0 and score >= 3 :
    st.error('لطفا امتیاز مناسب بدهید نظر شما ثبت نشد')
trigger = st.button('ثبت نظر',on_click=predict)
