# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GAe9KoRFyMqDQap0yCscjXhQJOzLAGU
"""

from transformers import pipeline
import joblib
import numpy as np
import pandas as pd
import gradio as gr

# بارگذاری مدل‌ها
model = joblib.load('mymodel.joblib')
sen = pipeline('sentiment-analysis', model='HooshvareLab/bert-fa-base-uncased-sentiment-snappfood')

def process_review(sent, ops, neg, score):
    """
    پردازش نظر کاربر و تصمیم‌گیری برای ثبت
    """
    # تحلیل احساس متن
    sentf = sen(sent)

    # تبدیل احساس به عدد
    des = 1 if sentf[0]['label'] == 'HAPPY' else 0

    # پیش‌بینی با مدل
    raw = np.array([[des, ops, neg]])
    x = pd.DataFrame(raw, columns=['des', 'pos', 'neg']) # Changed 'ops' to 'pos' here
    pre = model.predict(x)[0]

    # تصمیم‌گیری نهایی
    if pre == 1 and score >= 3:
        return "✅ نظر شما ثبت شد", "success"
    elif pre == 1 and score < 3:
        return "❌ لطفا امتیاز مناسب بدهید. نظر شما ثبت نشد.", "error"
    elif pre == 0 and score < 3:
        return "✅ نظر شما ثبت شد", "success"
    elif pre == 0 and score >= 3:
        return "❌ لطفا امتیاز مناسب بدهید. نظر شما ثبت نشد.", "error"
    else:
        return "⚠️ خطا در پردازش", "warning"

def get_sentiment_label(text):
    """نمایش تحلیل احساس متن"""
    if not text:
        return "متن وارد نشده"

    result = sen(text)
    label = result[0]['label']
    score = result[0]['score']

    if label == 'HAPPY':
        return f"😊 مثبت (اطمینان: {score:.2%})"
    else:
        return f"😞 منفی (اطمینان: {score:.2%})"

# ایجاد رابط Gradio
with gr.Blocks(title="ویرایشگر نظر خریدار", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🛍️ ویرایشگر نظر خریدار")
    gr.Markdown("نظر خود را در مورد کالا وارد کنید و تنظیمات مربوطه را اعمال نمایید.")

    with gr.Row():
        with gr.Column(scale=2):
            sent = gr.Textbox(
                label="نظر خود را راجب کالا وارد کنید",
                placeholder="مثال: این محصول کیفیت فوق‌العاده‌ای دارد...",
                lines=4
            )

            # نمایش تحلیل احساس به صورت real-time
            sentiment_output = gr.Textbox(
                label="تحلیل احساس متن",
                interactive=False
            )

            sent.change(
                fn=get_sentiment_label,
                inputs=sent,
                outputs=sentiment_output
            )

        with gr.Column(scale=1):
            ops = gr.Slider(
                minimum=0,
                maximum=3,
                value=1,
                step=1,
                label="تعداد نقاط قوت"
            )

            neg = gr.Slider(
                minimum=0,
                maximum=3,
                value=1,
                step=1,
                label="تعداد نقاط ضعف"
            )

            score = gr.Radio(
                choices=[1, 2, 3, 4, 5],
                value=3,
                label="امتیاز کالا",
                info="از ۱ تا ۵ امتیاز دهید"
            )

    # دکمه ثبت
    submit_btn = gr.Button("📝 ثبت نظر", variant="primary")

    # خروجی‌ها
    with gr.Row():
        result_output = gr.Textbox(
            label="نتیجه ثبت نظر",
            interactive=False
        )

        status_output = gr.Textbox(
            label="وضعیت",
            interactive=False
        )

    # رویداد کلیک
    submit_btn.click(
        fn=process_review,
        inputs=[sent, ops, neg, score],
        outputs=[result_output, status_output]
    )

    # مثال‌های آماده
    gr.Markdown("### مثال‌های آماده")
    examples = [
        ["این محصول واقعا عالی است و کیفیت فوق‌العاده‌ای دارد", 2, 1, 5],
        ["کیفیت پایین و بسته‌بندی ضعیف", 1, 2, 2],
        ["قیمت مناسب اما دوام کم", 2, 2, 3]
    ]

    gr.Examples(
        examples=examples,
        inputs=[sent, ops, neg, score],
        outputs=[result_output, status_output],fn=process_review,
        cache_examples=True
    )

    # راهنمای استفاده
    with gr.Accordion("📖 راهنمای استفاده", open=False):
        gr.Markdown("""
        نحوه استفاده:
        1. نظر خود را در مورد کالا بنویسید
        2. تعداد نقاط قوت و ضعف را مشخص کنید
        3. امتیاز ۱ تا ۵ به کالا دهید
        4. دکمه ثبت نظر را بفشارید

        نکات:
        - سیستم به طور خودکار احساس متن را تحلیل می‌کند
        - ترکیب احساس، امتیاز و نقاط قوت/ضعفت تصمیم نهایی را می‌گیرد
        """)
name = 'main'
# اجرای برنامه
if name == "main":
    demo.launch(
        server_name="0.0.0.0",
        server_port=7861, # Changed port to 7861
        share=True,  # برای لینک عمومی True کنید
        debug=True
    )